<a href="https://colab.research.google.com/github/savarirohan3-byte/AIDS-Learning/blob/main/3_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import spacy

In [ ]:
nlp=spacy.load('en_core_web_sm')

In [ ]:
nlp(u'lion').vector

array([-0.37331197, -0.636077  ,  0.16624087, -0.4500625 ,  0.02346338,
       -0.03507689,  1.2888179 ,  0.5569869 ,  0.00782521,  0.03196311,
        0.53636825, -0.53003603, -0.5546204 ,  0.07603534, -0.6676563 ,
        0.64938223, -0.57278097, -0.42561203,  0.78977346,  0.23432143,
       -0.4744925 ,  1.4517382 , -0.6984429 ,  0.17191873,  0.57576656,
        0.8409606 ,  0.5306976 , -0.16426727, -0.31692672,  1.1624684 ,
       -0.02932239,  0.6820288 , -0.09631193,  0.4340958 , -0.7869414 ,
       -0.67758393,  0.15711513,  0.77149993, -0.42237112,  0.43566388,
       -0.48777014,  0.05853128,  0.10582243,  0.6809435 ,  0.2115672 ,
        0.31190214, -0.5367352 , -0.71792245, -0.7814528 , -0.5595007 ,
       -0.06030444, -0.235009  ,  0.14786157, -0.9114496 , -0.04370221,
        0.33902794,  1.3769817 ,  0.03151399, -0.01746303,  0.17750838,
       -0.8129017 , -0.08208682, -0.45948845, -0.25383136, -0.22368991,
        0.00536951,  0.355986  , -0.08492555, -1.2826453 , -0.31

In [ ]:
doc=nlp(u'The quick brown fox jumped over the lazy dog.')
doc.vector

array([ 0.3325715 , -0.43228206,  0.03171952,  0.13252804, -0.34215504,
        0.08004382, -0.04001777, -0.14894801,  0.19675681, -0.09497433,
        0.11113968,  0.59827995, -0.04022352, -0.00912878, -0.25561267,
        0.26009136, -0.37257344,  0.23390023,  0.0767727 ,  0.04742187,
       -0.39871222,  0.09645335,  0.05040834, -0.52172667,  0.33559594,
       -0.05657964,  0.04954121, -0.21714482,  0.29679155,  0.1352779 ,
        0.33971244, -0.4833695 ,  0.06098223, -0.25901088, -0.3571213 ,
       -0.03227443,  0.1713001 ,  0.19476104,  0.00406475, -0.09610181,
        0.18606785,  0.4507466 , -0.09274605, -0.06959991,  0.09818505,
       -0.09226308, -0.02238299,  0.45828646,  0.20718054,  0.19536361,
        0.17991173,  0.22856489, -0.17108454, -0.0075765 , -0.4095992 ,
        0.50101686,  0.02041239,  0.2487971 , -0.18977678,  0.0855552 ,
       -0.24700205, -0.19493549, -0.23766005, -0.5379799 , -0.14567743,
       -0.3232315 ,  0.25214216, -0.36662254, -0.10849714, -0.32

In [ ]:
tokens=nlp(u'lion cat pet')
tokens

lion cat pet

In [ ]:
for token1 in tokens:
  for token2 in tokens:
    print(token1.text,token2.text,token1.similarity(token2))

lion lion 1.0
lion cat 0.7044516205787659
lion pet 0.3186751902103424
cat lion 0.7044516205787659
cat cat 1.0
cat pet 0.36159902811050415
pet lion 0.3186751902103424
pet cat 0.36159902811050415
pet pet 1.0


/tmp/ipython-input-914047137.py:3: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Token.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  print(token1.text,token2.text,token1.similarity(token2))


In [ ]:
nlp(u'lion').similarity(nlp(u'dandelion'))

/tmp/ipython-input-1276038593.py:1: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  nlp(u'lion').similarity(nlp(u'dandelion'))


0.7058143615722656

In [ ]:
tokens=nlp(u'like love hate')
tokens

like love hate

In [ ]:
for token1 in tokens:
  for token2 in tokens:
    print(token1.text,token2.text,token1.similarity(token2))

like like 1.0
like love -0.16221697628498077
like hate 0.1207711398601532
love like -0.16221697628498077
love love 1.0
love hate 0.2791391909122467
hate like 0.1207711398601532
hate love 0.2791391909122467
hate hate 1.0


/tmp/ipython-input-914047137.py:3: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Token.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  print(token1.text,token2.text,token1.similarity(token2))


In [ ]:
import nltk

In [ ]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...


True

In [ ]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [ ]:
sid=SentimentIntensityAnalyzer()

In [ ]:
a='this is a good moive'

In [ ]:
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.508, 'pos': 0.492, 'compound': 0.4404}

In [ ]:
a='This was the best, most awesome movie EVER MADE!!!'
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.425, 'pos': 0.575, 'compound': 0.8877}

In [ ]:
a='This was the worst film to ever disgrace the screen.'
sid.polarity_scores(a)

{'neg': 0.477, 'neu': 0.523, 'pos': 0.0, 'compound': -0.8074}

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('amazonreviews.tsv',sep='\t')
df.head()

label                                             review
0   pos  Stuning even for the non-gamer: This sound tra...
1   pos  The best soundtrack ever to anything.: I'm rea...
2   pos  Amazing!: This soundtrack is my favorite music...
3   pos  Excellent Soundtrack: I truly like this soundt...
4   pos  Remember, Pull Your Jaw Off The Floor After He...

In [ ]:
df['label'].value_counts()

label
neg    5097
pos    4903
Name: count, dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df['label'].value_counts()

label
neg    5097
pos    4903
Name: count, dtype: int64

In [ ]:
blanks=[]
for i,lb,rv in df.itertuples():
  if type(rv)==str:
    if rv.isspace():
      blanks.append(i)

In [ ]:
df.drop(blanks,inplace = True)

In [ ]:
df['label'].value_counts

<bound method IndexOpsMixin.value_counts of 0       pos
1       pos
2       pos
3       pos
4       pos
       ... 
9995    pos
9996    pos
9997    neg
9998    neg
9999    pos
Name: label, Length: 10000, dtype: object>

In [ ]:
sid.polarity_scores(df.loc[0]['review'])

{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'compound': 0.9454}

In [ ]:
df.loc[0]['label']

'pos'

In [ ]:
df['scores']=df['review'].apply(lambda review:sid.polarity_scores(review))
df.head()

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...

In [ ]:
sid.polarity_scores(df.loc[0]['review'])
df.loc[0]['scores']

{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'compound': 0.9454}

In [ ]:
df['comp_score']=df['scores'].apply(lambda x: 'pos' if x['compound'] >=0 else 'neg')
df.head()

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores comp_score  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...        pos  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...        pos  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...        pos  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...        pos  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...        pos

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
accuracy_score(df['label'],df['comp_score'])

0.7098

In [ ]:
print(confusion_matrix(df['label'],df['comp_score']))

[[2630 2467]
 [ 435 4468]]


In [ ]:
print(classification_report(df['label'],df['comp_score']))

              precision    recall  f1-score   support

         neg       0.86      0.52      0.64      5097
         pos       0.64      0.91      0.75      4903

    accuracy                           0.71     10000
   macro avg       0.75      0.71      0.70     10000
weighted avg       0.75      0.71      0.70     10000



In [47]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler

# Assuming 'df' is your DataFrame with 'review' and 'label' columns
# Define features (X) and target (y)
X = df['review']
y = df['label']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Vectorize the text data using TF-IDF
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

# Initialize and fit the scaler on the training data
# Use with_mean=False for sparse matrices produced by TF-IDFVectorizer
scaler = StandardScaler(with_mean=False)
scaler.fit(X_train_tfidf)

# Scale the training and test features
scaled_X_train = scaler.transform(X_train_tfidf)
scaled_X_test = scaler.transform(X_test_tfidf)

In [45]:
X_train.max()

'~ Erotic Fantasy ~: This is a lovely erotic fantasy. There are glimpses of BDSM but it is not "hardcore".Do not compare this book to the movie of the same name ~ The movie version is camped up & changed to make the story light & funny ~ The actual story in this book is not light and not funny, it is more of a complicated romance, between two people who don\'t realize how much they need each other.I thoroughly enjoyed this book and hopefully, you will too ~ and if you do, you may seriously want to pick up the Sleeping Beauty Trilogy.'

In [48]:
scaled_X_train.max()

np.float64(89.4483097940684)

In [49]:
scaled_X_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 442230 stored elements and shape (8000, 28031)>

In [50]:
from keras.models import Sequential
from keras.layers import Dense

In [51]:
import tensorflow as tf

In [52]:
model=Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
